/*
OpenPay API

Testing BillingMeterEventAdjustmentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package getopenpay

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/getopenpay/getopenpay-go"
)

func Test_getopenpay_BillingMeterEventAdjustmentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BillingMeterEventAdjustmentsAPIService CreateBillingMeterEventAdjustments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BillingMeterEventAdjustmentsAPI.CreateBillingMeterEventAdjustments(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
