/*
OpenPay API

super charge your subscription management.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getopenpay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdatePaymentRouteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePaymentRouteRequest{}

// UpdatePaymentRouteRequest struct for UpdatePaymentRouteRequest
type UpdatePaymentRouteRequest struct {
	// The name of the payment route.
	Name string `json:"name"`
	// The configuration object for the payment route. Contact the OpenPay team for more information.
	RouteConfiguration map[string]interface{} `json:"route_configuration"`
}

type _UpdatePaymentRouteRequest UpdatePaymentRouteRequest

// NewUpdatePaymentRouteRequest instantiates a new UpdatePaymentRouteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePaymentRouteRequest(name string, routeConfiguration map[string]interface{}) *UpdatePaymentRouteRequest {
	this := UpdatePaymentRouteRequest{}
	this.Name = name
	this.RouteConfiguration = routeConfiguration
	return &this
}

// NewUpdatePaymentRouteRequestWithDefaults instantiates a new UpdatePaymentRouteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePaymentRouteRequestWithDefaults() *UpdatePaymentRouteRequest {
	this := UpdatePaymentRouteRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UpdatePaymentRouteRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdatePaymentRouteRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdatePaymentRouteRequest) SetName(v string) {
	o.Name = v
}

// GetRouteConfiguration returns the RouteConfiguration field value
func (o *UpdatePaymentRouteRequest) GetRouteConfiguration() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.RouteConfiguration
}

// GetRouteConfigurationOk returns a tuple with the RouteConfiguration field value
// and a boolean to check if the value has been set.
func (o *UpdatePaymentRouteRequest) GetRouteConfigurationOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.RouteConfiguration, true
}

// SetRouteConfiguration sets field value
func (o *UpdatePaymentRouteRequest) SetRouteConfiguration(v map[string]interface{}) {
	o.RouteConfiguration = v
}

func (o UpdatePaymentRouteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePaymentRouteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["route_configuration"] = o.RouteConfiguration
	return toSerialize, nil
}

func (o *UpdatePaymentRouteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"route_configuration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePaymentRouteRequest := _UpdatePaymentRouteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePaymentRouteRequest)

	if err != nil {
		return err
	}

	*o = UpdatePaymentRouteRequest(varUpdatePaymentRouteRequest)

	return err
}

type NullableUpdatePaymentRouteRequest struct {
	value *UpdatePaymentRouteRequest
	isSet bool
}

func (v NullableUpdatePaymentRouteRequest) Get() *UpdatePaymentRouteRequest {
	return v.value
}

func (v *NullableUpdatePaymentRouteRequest) Set(val *UpdatePaymentRouteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePaymentRouteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePaymentRouteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePaymentRouteRequest(val *UpdatePaymentRouteRequest) *NullableUpdatePaymentRouteRequest {
	return &NullableUpdatePaymentRouteRequest{value: val, isSet: true}
}

func (v NullableUpdatePaymentRouteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePaymentRouteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


