/*
OpenPay API

super charge your subscription management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getopenpay

import (
	"encoding/json"
)

// checks if the DeleteSubscriptionItemRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteSubscriptionItemRequest{}

// DeleteSubscriptionItemRequest struct for DeleteSubscriptionItemRequest
type DeleteSubscriptionItemRequest struct {
	// Whether or not this item will be dropped from subscription before next renewal
	DropAtEnd *bool `json:"drop_at_end,omitempty"`
	ProrationBehavior *ProrationEnum `json:"proration_behavior,omitempty"`
}

// NewDeleteSubscriptionItemRequest instantiates a new DeleteSubscriptionItemRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteSubscriptionItemRequest() *DeleteSubscriptionItemRequest {
	this := DeleteSubscriptionItemRequest{}
	var dropAtEnd bool = true
	this.DropAtEnd = &dropAtEnd
	var prorationBehavior ProrationEnum = PRORATIONENUM_ALWAYS_INVOICE
	this.ProrationBehavior = &prorationBehavior
	return &this
}

// NewDeleteSubscriptionItemRequestWithDefaults instantiates a new DeleteSubscriptionItemRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteSubscriptionItemRequestWithDefaults() *DeleteSubscriptionItemRequest {
	this := DeleteSubscriptionItemRequest{}
	var dropAtEnd bool = true
	this.DropAtEnd = &dropAtEnd
	var prorationBehavior ProrationEnum = PRORATIONENUM_ALWAYS_INVOICE
	this.ProrationBehavior = &prorationBehavior
	return &this
}

// GetDropAtEnd returns the DropAtEnd field value if set, zero value otherwise.
func (o *DeleteSubscriptionItemRequest) GetDropAtEnd() bool {
	if o == nil || IsNil(o.DropAtEnd) {
		var ret bool
		return ret
	}
	return *o.DropAtEnd
}

// GetDropAtEndOk returns a tuple with the DropAtEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteSubscriptionItemRequest) GetDropAtEndOk() (*bool, bool) {
	if o == nil || IsNil(o.DropAtEnd) {
		return nil, false
	}
	return o.DropAtEnd, true
}

// HasDropAtEnd returns a boolean if a field has been set.
func (o *DeleteSubscriptionItemRequest) HasDropAtEnd() bool {
	if o != nil && !IsNil(o.DropAtEnd) {
		return true
	}

	return false
}

// SetDropAtEnd gets a reference to the given bool and assigns it to the DropAtEnd field.
func (o *DeleteSubscriptionItemRequest) SetDropAtEnd(v bool) {
	o.DropAtEnd = &v
}

// GetProrationBehavior returns the ProrationBehavior field value if set, zero value otherwise.
func (o *DeleteSubscriptionItemRequest) GetProrationBehavior() ProrationEnum {
	if o == nil || IsNil(o.ProrationBehavior) {
		var ret ProrationEnum
		return ret
	}
	return *o.ProrationBehavior
}

// GetProrationBehaviorOk returns a tuple with the ProrationBehavior field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteSubscriptionItemRequest) GetProrationBehaviorOk() (*ProrationEnum, bool) {
	if o == nil || IsNil(o.ProrationBehavior) {
		return nil, false
	}
	return o.ProrationBehavior, true
}

// HasProrationBehavior returns a boolean if a field has been set.
func (o *DeleteSubscriptionItemRequest) HasProrationBehavior() bool {
	if o != nil && !IsNil(o.ProrationBehavior) {
		return true
	}

	return false
}

// SetProrationBehavior gets a reference to the given ProrationEnum and assigns it to the ProrationBehavior field.
func (o *DeleteSubscriptionItemRequest) SetProrationBehavior(v ProrationEnum) {
	o.ProrationBehavior = &v
}

func (o DeleteSubscriptionItemRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteSubscriptionItemRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DropAtEnd) {
		toSerialize["drop_at_end"] = o.DropAtEnd
	}
	if !IsNil(o.ProrationBehavior) {
		toSerialize["proration_behavior"] = o.ProrationBehavior
	}
	return toSerialize, nil
}

type NullableDeleteSubscriptionItemRequest struct {
	value *DeleteSubscriptionItemRequest
	isSet bool
}

func (v NullableDeleteSubscriptionItemRequest) Get() *DeleteSubscriptionItemRequest {
	return v.value
}

func (v *NullableDeleteSubscriptionItemRequest) Set(val *DeleteSubscriptionItemRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteSubscriptionItemRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteSubscriptionItemRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteSubscriptionItemRequest(val *DeleteSubscriptionItemRequest) *NullableDeleteSubscriptionItemRequest {
	return &NullableDeleteSubscriptionItemRequest{value: val, isSet: true}
}

func (v NullableDeleteSubscriptionItemRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteSubscriptionItemRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


