/*
OpenPay API

super charge your subscription management.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getopenpay

import (
	"encoding/json"
)

// checks if the InvoiceItemDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceItemDetails{}

// InvoiceItemDetails struct for InvoiceItemDetails
type InvoiceItemDetails struct {
	Description NullableString `json:"description,omitempty"`
}

// NewInvoiceItemDetails instantiates a new InvoiceItemDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceItemDetails() *InvoiceItemDetails {
	this := InvoiceItemDetails{}
	return &this
}

// NewInvoiceItemDetailsWithDefaults instantiates a new InvoiceItemDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceItemDetailsWithDefaults() *InvoiceItemDetails {
	this := InvoiceItemDetails{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InvoiceItemDetails) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvoiceItemDetails) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *InvoiceItemDetails) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *InvoiceItemDetails) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *InvoiceItemDetails) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *InvoiceItemDetails) UnsetDescription() {
	o.Description.Unset()
}

func (o InvoiceItemDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceItemDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	return toSerialize, nil
}

type NullableInvoiceItemDetails struct {
	value *InvoiceItemDetails
	isSet bool
}

func (v NullableInvoiceItemDetails) Get() *InvoiceItemDetails {
	return v.value
}

func (v *NullableInvoiceItemDetails) Set(val *InvoiceItemDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceItemDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceItemDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceItemDetails(val *InvoiceItemDetails) *NullableInvoiceItemDetails {
	return &NullableInvoiceItemDetails{value: val, isSet: true}
}

func (v NullableInvoiceItemDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceItemDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


