/*
OpenPay API

super charge your subscription management.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getopenpay

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CustomerBalanceTransactionExternal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerBalanceTransactionExternal{}

// CustomerBalanceTransactionExternal struct for CustomerBalanceTransactionExternal
type CustomerBalanceTransactionExternal struct {
	AmountAtom int32 `json:"amount_atom"`
	// DateTime at which the object was created, in 'ISO 8601' format.
	CreatedAt time.Time `json:"created_at"`
	CreditNoteId NullableString `json:"credit_note_id"`
	Currency CurrencyEnum `json:"currency"`
	Description NullableString `json:"description"`
	EndingBalanceAmountAtom int32 `json:"ending_balance_amount_atom"`
	Id string `json:"id"`
	InvoiceId NullableString `json:"invoice_id"`
	// If true, indicates that this object has been deleted
	IsDeleted *bool `json:"is_deleted,omitempty"`
	Object *ObjectName `json:"object,omitempty"`
	Type CustomerBalanceTransactionType `json:"type"`
	// DateTime at which the object was updated, in 'ISO 8601' format.
	UpdatedAt time.Time `json:"updated_at"`
}

type _CustomerBalanceTransactionExternal CustomerBalanceTransactionExternal

// NewCustomerBalanceTransactionExternal instantiates a new CustomerBalanceTransactionExternal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerBalanceTransactionExternal(amountAtom int32, createdAt time.Time, creditNoteId NullableString, currency CurrencyEnum, description NullableString, endingBalanceAmountAtom int32, id string, invoiceId NullableString, type_ CustomerBalanceTransactionType, updatedAt time.Time) *CustomerBalanceTransactionExternal {
	this := CustomerBalanceTransactionExternal{}
	this.AmountAtom = amountAtom
	this.CreatedAt = createdAt
	this.CreditNoteId = creditNoteId
	this.Currency = currency
	this.Description = description
	this.EndingBalanceAmountAtom = endingBalanceAmountAtom
	this.Id = id
	this.InvoiceId = invoiceId
	var isDeleted bool = false
	this.IsDeleted = &isDeleted
	this.Type = type_
	this.UpdatedAt = updatedAt
	return &this
}

// NewCustomerBalanceTransactionExternalWithDefaults instantiates a new CustomerBalanceTransactionExternal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerBalanceTransactionExternalWithDefaults() *CustomerBalanceTransactionExternal {
	this := CustomerBalanceTransactionExternal{}
	var isDeleted bool = false
	this.IsDeleted = &isDeleted
	return &this
}

// GetAmountAtom returns the AmountAtom field value
func (o *CustomerBalanceTransactionExternal) GetAmountAtom() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AmountAtom
}

// GetAmountAtomOk returns a tuple with the AmountAtom field value
// and a boolean to check if the value has been set.
func (o *CustomerBalanceTransactionExternal) GetAmountAtomOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountAtom, true
}

// SetAmountAtom sets field value
func (o *CustomerBalanceTransactionExternal) SetAmountAtom(v int32) {
	o.AmountAtom = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CustomerBalanceTransactionExternal) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CustomerBalanceTransactionExternal) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CustomerBalanceTransactionExternal) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCreditNoteId returns the CreditNoteId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CustomerBalanceTransactionExternal) GetCreditNoteId() string {
	if o == nil || o.CreditNoteId.Get() == nil {
		var ret string
		return ret
	}

	return *o.CreditNoteId.Get()
}

// GetCreditNoteIdOk returns a tuple with the CreditNoteId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerBalanceTransactionExternal) GetCreditNoteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreditNoteId.Get(), o.CreditNoteId.IsSet()
}

// SetCreditNoteId sets field value
func (o *CustomerBalanceTransactionExternal) SetCreditNoteId(v string) {
	o.CreditNoteId.Set(&v)
}

// GetCurrency returns the Currency field value
func (o *CustomerBalanceTransactionExternal) GetCurrency() CurrencyEnum {
	if o == nil {
		var ret CurrencyEnum
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *CustomerBalanceTransactionExternal) GetCurrencyOk() (*CurrencyEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *CustomerBalanceTransactionExternal) SetCurrency(v CurrencyEnum) {
	o.Currency = v
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CustomerBalanceTransactionExternal) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerBalanceTransactionExternal) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *CustomerBalanceTransactionExternal) SetDescription(v string) {
	o.Description.Set(&v)
}

// GetEndingBalanceAmountAtom returns the EndingBalanceAmountAtom field value
func (o *CustomerBalanceTransactionExternal) GetEndingBalanceAmountAtom() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EndingBalanceAmountAtom
}

// GetEndingBalanceAmountAtomOk returns a tuple with the EndingBalanceAmountAtom field value
// and a boolean to check if the value has been set.
func (o *CustomerBalanceTransactionExternal) GetEndingBalanceAmountAtomOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndingBalanceAmountAtom, true
}

// SetEndingBalanceAmountAtom sets field value
func (o *CustomerBalanceTransactionExternal) SetEndingBalanceAmountAtom(v int32) {
	o.EndingBalanceAmountAtom = v
}

// GetId returns the Id field value
func (o *CustomerBalanceTransactionExternal) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomerBalanceTransactionExternal) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomerBalanceTransactionExternal) SetId(v string) {
	o.Id = v
}

// GetInvoiceId returns the InvoiceId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CustomerBalanceTransactionExternal) GetInvoiceId() string {
	if o == nil || o.InvoiceId.Get() == nil {
		var ret string
		return ret
	}

	return *o.InvoiceId.Get()
}

// GetInvoiceIdOk returns a tuple with the InvoiceId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerBalanceTransactionExternal) GetInvoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InvoiceId.Get(), o.InvoiceId.IsSet()
}

// SetInvoiceId sets field value
func (o *CustomerBalanceTransactionExternal) SetInvoiceId(v string) {
	o.InvoiceId.Set(&v)
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *CustomerBalanceTransactionExternal) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerBalanceTransactionExternal) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *CustomerBalanceTransactionExternal) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *CustomerBalanceTransactionExternal) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *CustomerBalanceTransactionExternal) GetObject() ObjectName {
	if o == nil || IsNil(o.Object) {
		var ret ObjectName
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerBalanceTransactionExternal) GetObjectOk() (*ObjectName, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *CustomerBalanceTransactionExternal) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given ObjectName and assigns it to the Object field.
func (o *CustomerBalanceTransactionExternal) SetObject(v ObjectName) {
	o.Object = &v
}

// GetType returns the Type field value
func (o *CustomerBalanceTransactionExternal) GetType() CustomerBalanceTransactionType {
	if o == nil {
		var ret CustomerBalanceTransactionType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CustomerBalanceTransactionExternal) GetTypeOk() (*CustomerBalanceTransactionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CustomerBalanceTransactionExternal) SetType(v CustomerBalanceTransactionType) {
	o.Type = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *CustomerBalanceTransactionExternal) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *CustomerBalanceTransactionExternal) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *CustomerBalanceTransactionExternal) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o CustomerBalanceTransactionExternal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerBalanceTransactionExternal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount_atom"] = o.AmountAtom
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["credit_note_id"] = o.CreditNoteId.Get()
	toSerialize["currency"] = o.Currency
	toSerialize["description"] = o.Description.Get()
	toSerialize["ending_balance_amount_atom"] = o.EndingBalanceAmountAtom
	toSerialize["id"] = o.Id
	toSerialize["invoice_id"] = o.InvoiceId.Get()
	if !IsNil(o.IsDeleted) {
		toSerialize["is_deleted"] = o.IsDeleted
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	toSerialize["type"] = o.Type
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *CustomerBalanceTransactionExternal) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount_atom",
		"created_at",
		"credit_note_id",
		"currency",
		"description",
		"ending_balance_amount_atom",
		"id",
		"invoice_id",
		"type",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerBalanceTransactionExternal := _CustomerBalanceTransactionExternal{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomerBalanceTransactionExternal)

	if err != nil {
		return err
	}

	*o = CustomerBalanceTransactionExternal(varCustomerBalanceTransactionExternal)

	return err
}

type NullableCustomerBalanceTransactionExternal struct {
	value *CustomerBalanceTransactionExternal
	isSet bool
}

func (v NullableCustomerBalanceTransactionExternal) Get() *CustomerBalanceTransactionExternal {
	return v.value
}

func (v *NullableCustomerBalanceTransactionExternal) Set(val *CustomerBalanceTransactionExternal) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerBalanceTransactionExternal) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerBalanceTransactionExternal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerBalanceTransactionExternal(val *CustomerBalanceTransactionExternal) *NullableCustomerBalanceTransactionExternal {
	return &NullableCustomerBalanceTransactionExternal{value: val, isSet: true}
}

func (v NullableCustomerBalanceTransactionExternal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerBalanceTransactionExternal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


