/*
OpenPay API

super charge your subscription management.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getopenpay

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TaxIntegrationExternal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaxIntegrationExternal{}

// TaxIntegrationExternal struct for TaxIntegrationExternal
type TaxIntegrationExternal struct {
	// The timezone name for the accounting timezone (see pytz.all_timezones for a full list)
	AccountingTz string `json:"accounting_tz"`
	// These keys will allow to authenticate API requests to the tax processor.
	ApiKeys map[string]interface{} `json:"api_keys"`
	// The name of the API used for the tax integration.
	ApiName TaxIntegrationApiName `json:"api_name"`
	// DateTime at which the object was created, in 'ISO 8601' format.
	CreatedAt time.Time `json:"created_at"`
	// Unique Identifier of the tax integration.
	Id string `json:"id"`
	// If true, indicates that this object has been deleted
	IsDeleted *bool `json:"is_deleted,omitempty"`
	Object *ObjectName `json:"object,omitempty"`
	// DateTime at which the object was updated, in 'ISO 8601' format.
	UpdatedAt time.Time `json:"updated_at"`
}

type _TaxIntegrationExternal TaxIntegrationExternal

// NewTaxIntegrationExternal instantiates a new TaxIntegrationExternal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaxIntegrationExternal(accountingTz string, apiKeys map[string]interface{}, apiName TaxIntegrationApiName, createdAt time.Time, id string, updatedAt time.Time) *TaxIntegrationExternal {
	this := TaxIntegrationExternal{}
	this.AccountingTz = accountingTz
	this.ApiKeys = apiKeys
	this.ApiName = apiName
	this.CreatedAt = createdAt
	this.Id = id
	var isDeleted bool = false
	this.IsDeleted = &isDeleted
	this.UpdatedAt = updatedAt
	return &this
}

// NewTaxIntegrationExternalWithDefaults instantiates a new TaxIntegrationExternal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaxIntegrationExternalWithDefaults() *TaxIntegrationExternal {
	this := TaxIntegrationExternal{}
	var isDeleted bool = false
	this.IsDeleted = &isDeleted
	return &this
}

// GetAccountingTz returns the AccountingTz field value
func (o *TaxIntegrationExternal) GetAccountingTz() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountingTz
}

// GetAccountingTzOk returns a tuple with the AccountingTz field value
// and a boolean to check if the value has been set.
func (o *TaxIntegrationExternal) GetAccountingTzOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountingTz, true
}

// SetAccountingTz sets field value
func (o *TaxIntegrationExternal) SetAccountingTz(v string) {
	o.AccountingTz = v
}

// GetApiKeys returns the ApiKeys field value
func (o *TaxIntegrationExternal) GetApiKeys() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ApiKeys
}

// GetApiKeysOk returns a tuple with the ApiKeys field value
// and a boolean to check if the value has been set.
func (o *TaxIntegrationExternal) GetApiKeysOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.ApiKeys, true
}

// SetApiKeys sets field value
func (o *TaxIntegrationExternal) SetApiKeys(v map[string]interface{}) {
	o.ApiKeys = v
}

// GetApiName returns the ApiName field value
func (o *TaxIntegrationExternal) GetApiName() TaxIntegrationApiName {
	if o == nil {
		var ret TaxIntegrationApiName
		return ret
	}

	return o.ApiName
}

// GetApiNameOk returns a tuple with the ApiName field value
// and a boolean to check if the value has been set.
func (o *TaxIntegrationExternal) GetApiNameOk() (*TaxIntegrationApiName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiName, true
}

// SetApiName sets field value
func (o *TaxIntegrationExternal) SetApiName(v TaxIntegrationApiName) {
	o.ApiName = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TaxIntegrationExternal) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TaxIntegrationExternal) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TaxIntegrationExternal) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *TaxIntegrationExternal) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TaxIntegrationExternal) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TaxIntegrationExternal) SetId(v string) {
	o.Id = v
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *TaxIntegrationExternal) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxIntegrationExternal) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *TaxIntegrationExternal) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *TaxIntegrationExternal) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *TaxIntegrationExternal) GetObject() ObjectName {
	if o == nil || IsNil(o.Object) {
		var ret ObjectName
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxIntegrationExternal) GetObjectOk() (*ObjectName, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *TaxIntegrationExternal) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given ObjectName and assigns it to the Object field.
func (o *TaxIntegrationExternal) SetObject(v ObjectName) {
	o.Object = &v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *TaxIntegrationExternal) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *TaxIntegrationExternal) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *TaxIntegrationExternal) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o TaxIntegrationExternal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaxIntegrationExternal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accounting_tz"] = o.AccountingTz
	toSerialize["api_keys"] = o.ApiKeys
	toSerialize["api_name"] = o.ApiName
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["id"] = o.Id
	if !IsNil(o.IsDeleted) {
		toSerialize["is_deleted"] = o.IsDeleted
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *TaxIntegrationExternal) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accounting_tz",
		"api_keys",
		"api_name",
		"created_at",
		"id",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaxIntegrationExternal := _TaxIntegrationExternal{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTaxIntegrationExternal)

	if err != nil {
		return err
	}

	*o = TaxIntegrationExternal(varTaxIntegrationExternal)

	return err
}

type NullableTaxIntegrationExternal struct {
	value *TaxIntegrationExternal
	isSet bool
}

func (v NullableTaxIntegrationExternal) Get() *TaxIntegrationExternal {
	return v.value
}

func (v *NullableTaxIntegrationExternal) Set(val *TaxIntegrationExternal) {
	v.value = val
	v.isSet = true
}

func (v NullableTaxIntegrationExternal) IsSet() bool {
	return v.isSet
}

func (v *NullableTaxIntegrationExternal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaxIntegrationExternal(val *TaxIntegrationExternal) *NullableTaxIntegrationExternal {
	return &NullableTaxIntegrationExternal{value: val, isSet: true}
}

func (v NullableTaxIntegrationExternal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaxIntegrationExternal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


