/*
OpenPay API

super charge your subscription management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getopenpay

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the CreatePaymentLinkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePaymentLinkRequest{}

// CreatePaymentLinkRequest struct for CreatePaymentLinkRequest
type CreatePaymentLinkRequest struct {
	CouponId NullableString `json:"coupon_id,omitempty"`
	CustomerId NullableString `json:"customer_id,omitempty"`
	LineItems []CreateCheckoutLineItem `json:"line_items,omitempty"`
	Mode CheckoutMode `json:"mode"`
	SuccessUrl NullableString `json:"success_url"`
	TrialEnd NullableTime `json:"trial_end,omitempty"`
	TrialPeriodDays NullableInt32 `json:"trial_period_days,omitempty"`
	TrialFromPrice NullableBool `json:"trial_from_price,omitempty"`
}

type _CreatePaymentLinkRequest CreatePaymentLinkRequest

// NewCreatePaymentLinkRequest instantiates a new CreatePaymentLinkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePaymentLinkRequest(mode CheckoutMode, successUrl NullableString) *CreatePaymentLinkRequest {
	this := CreatePaymentLinkRequest{}
	this.Mode = mode
	this.SuccessUrl = successUrl
	return &this
}

// NewCreatePaymentLinkRequestWithDefaults instantiates a new CreatePaymentLinkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePaymentLinkRequestWithDefaults() *CreatePaymentLinkRequest {
	this := CreatePaymentLinkRequest{}
	return &this
}

// GetCouponId returns the CouponId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePaymentLinkRequest) GetCouponId() string {
	if o == nil || IsNil(o.CouponId.Get()) {
		var ret string
		return ret
	}
	return *o.CouponId.Get()
}

// GetCouponIdOk returns a tuple with the CouponId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePaymentLinkRequest) GetCouponIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CouponId.Get(), o.CouponId.IsSet()
}

// HasCouponId returns a boolean if a field has been set.
func (o *CreatePaymentLinkRequest) HasCouponId() bool {
	if o != nil && o.CouponId.IsSet() {
		return true
	}

	return false
}

// SetCouponId gets a reference to the given NullableString and assigns it to the CouponId field.
func (o *CreatePaymentLinkRequest) SetCouponId(v string) {
	o.CouponId.Set(&v)
}
// SetCouponIdNil sets the value for CouponId to be an explicit nil
func (o *CreatePaymentLinkRequest) SetCouponIdNil() {
	o.CouponId.Set(nil)
}

// UnsetCouponId ensures that no value is present for CouponId, not even an explicit nil
func (o *CreatePaymentLinkRequest) UnsetCouponId() {
	o.CouponId.Unset()
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePaymentLinkRequest) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerId.Get()
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePaymentLinkRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerId.Get(), o.CustomerId.IsSet()
}

// HasCustomerId returns a boolean if a field has been set.
func (o *CreatePaymentLinkRequest) HasCustomerId() bool {
	if o != nil && o.CustomerId.IsSet() {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given NullableString and assigns it to the CustomerId field.
func (o *CreatePaymentLinkRequest) SetCustomerId(v string) {
	o.CustomerId.Set(&v)
}
// SetCustomerIdNil sets the value for CustomerId to be an explicit nil
func (o *CreatePaymentLinkRequest) SetCustomerIdNil() {
	o.CustomerId.Set(nil)
}

// UnsetCustomerId ensures that no value is present for CustomerId, not even an explicit nil
func (o *CreatePaymentLinkRequest) UnsetCustomerId() {
	o.CustomerId.Unset()
}

// GetLineItems returns the LineItems field value if set, zero value otherwise.
func (o *CreatePaymentLinkRequest) GetLineItems() []CreateCheckoutLineItem {
	if o == nil || IsNil(o.LineItems) {
		var ret []CreateCheckoutLineItem
		return ret
	}
	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePaymentLinkRequest) GetLineItemsOk() ([]CreateCheckoutLineItem, bool) {
	if o == nil || IsNil(o.LineItems) {
		return nil, false
	}
	return o.LineItems, true
}

// HasLineItems returns a boolean if a field has been set.
func (o *CreatePaymentLinkRequest) HasLineItems() bool {
	if o != nil && !IsNil(o.LineItems) {
		return true
	}

	return false
}

// SetLineItems gets a reference to the given []CreateCheckoutLineItem and assigns it to the LineItems field.
func (o *CreatePaymentLinkRequest) SetLineItems(v []CreateCheckoutLineItem) {
	o.LineItems = v
}

// GetMode returns the Mode field value
func (o *CreatePaymentLinkRequest) GetMode() CheckoutMode {
	if o == nil {
		var ret CheckoutMode
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *CreatePaymentLinkRequest) GetModeOk() (*CheckoutMode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *CreatePaymentLinkRequest) SetMode(v CheckoutMode) {
	o.Mode = v
}

// GetSuccessUrl returns the SuccessUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreatePaymentLinkRequest) GetSuccessUrl() string {
	if o == nil || o.SuccessUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.SuccessUrl.Get()
}

// GetSuccessUrlOk returns a tuple with the SuccessUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePaymentLinkRequest) GetSuccessUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SuccessUrl.Get(), o.SuccessUrl.IsSet()
}

// SetSuccessUrl sets field value
func (o *CreatePaymentLinkRequest) SetSuccessUrl(v string) {
	o.SuccessUrl.Set(&v)
}

// GetTrialEnd returns the TrialEnd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePaymentLinkRequest) GetTrialEnd() time.Time {
	if o == nil || IsNil(o.TrialEnd.Get()) {
		var ret time.Time
		return ret
	}
	return *o.TrialEnd.Get()
}

// GetTrialEndOk returns a tuple with the TrialEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePaymentLinkRequest) GetTrialEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrialEnd.Get(), o.TrialEnd.IsSet()
}

// HasTrialEnd returns a boolean if a field has been set.
func (o *CreatePaymentLinkRequest) HasTrialEnd() bool {
	if o != nil && o.TrialEnd.IsSet() {
		return true
	}

	return false
}

// SetTrialEnd gets a reference to the given NullableTime and assigns it to the TrialEnd field.
func (o *CreatePaymentLinkRequest) SetTrialEnd(v time.Time) {
	o.TrialEnd.Set(&v)
}
// SetTrialEndNil sets the value for TrialEnd to be an explicit nil
func (o *CreatePaymentLinkRequest) SetTrialEndNil() {
	o.TrialEnd.Set(nil)
}

// UnsetTrialEnd ensures that no value is present for TrialEnd, not even an explicit nil
func (o *CreatePaymentLinkRequest) UnsetTrialEnd() {
	o.TrialEnd.Unset()
}

// GetTrialPeriodDays returns the TrialPeriodDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePaymentLinkRequest) GetTrialPeriodDays() int32 {
	if o == nil || IsNil(o.TrialPeriodDays.Get()) {
		var ret int32
		return ret
	}
	return *o.TrialPeriodDays.Get()
}

// GetTrialPeriodDaysOk returns a tuple with the TrialPeriodDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePaymentLinkRequest) GetTrialPeriodDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrialPeriodDays.Get(), o.TrialPeriodDays.IsSet()
}

// HasTrialPeriodDays returns a boolean if a field has been set.
func (o *CreatePaymentLinkRequest) HasTrialPeriodDays() bool {
	if o != nil && o.TrialPeriodDays.IsSet() {
		return true
	}

	return false
}

// SetTrialPeriodDays gets a reference to the given NullableInt32 and assigns it to the TrialPeriodDays field.
func (o *CreatePaymentLinkRequest) SetTrialPeriodDays(v int32) {
	o.TrialPeriodDays.Set(&v)
}
// SetTrialPeriodDaysNil sets the value for TrialPeriodDays to be an explicit nil
func (o *CreatePaymentLinkRequest) SetTrialPeriodDaysNil() {
	o.TrialPeriodDays.Set(nil)
}

// UnsetTrialPeriodDays ensures that no value is present for TrialPeriodDays, not even an explicit nil
func (o *CreatePaymentLinkRequest) UnsetTrialPeriodDays() {
	o.TrialPeriodDays.Unset()
}

// GetTrialFromPrice returns the TrialFromPrice field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePaymentLinkRequest) GetTrialFromPrice() bool {
	if o == nil || IsNil(o.TrialFromPrice.Get()) {
		var ret bool
		return ret
	}
	return *o.TrialFromPrice.Get()
}

// GetTrialFromPriceOk returns a tuple with the TrialFromPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePaymentLinkRequest) GetTrialFromPriceOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrialFromPrice.Get(), o.TrialFromPrice.IsSet()
}

// HasTrialFromPrice returns a boolean if a field has been set.
func (o *CreatePaymentLinkRequest) HasTrialFromPrice() bool {
	if o != nil && o.TrialFromPrice.IsSet() {
		return true
	}

	return false
}

// SetTrialFromPrice gets a reference to the given NullableBool and assigns it to the TrialFromPrice field.
func (o *CreatePaymentLinkRequest) SetTrialFromPrice(v bool) {
	o.TrialFromPrice.Set(&v)
}
// SetTrialFromPriceNil sets the value for TrialFromPrice to be an explicit nil
func (o *CreatePaymentLinkRequest) SetTrialFromPriceNil() {
	o.TrialFromPrice.Set(nil)
}

// UnsetTrialFromPrice ensures that no value is present for TrialFromPrice, not even an explicit nil
func (o *CreatePaymentLinkRequest) UnsetTrialFromPrice() {
	o.TrialFromPrice.Unset()
}

func (o CreatePaymentLinkRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePaymentLinkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CouponId.IsSet() {
		toSerialize["coupon_id"] = o.CouponId.Get()
	}
	if o.CustomerId.IsSet() {
		toSerialize["customer_id"] = o.CustomerId.Get()
	}
	if !IsNil(o.LineItems) {
		toSerialize["line_items"] = o.LineItems
	}
	toSerialize["mode"] = o.Mode
	toSerialize["success_url"] = o.SuccessUrl.Get()
	if o.TrialEnd.IsSet() {
		toSerialize["trial_end"] = o.TrialEnd.Get()
	}
	if o.TrialPeriodDays.IsSet() {
		toSerialize["trial_period_days"] = o.TrialPeriodDays.Get()
	}
	if o.TrialFromPrice.IsSet() {
		toSerialize["trial_from_price"] = o.TrialFromPrice.Get()
	}
	return toSerialize, nil
}

func (o *CreatePaymentLinkRequest) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mode",
		"success_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePaymentLinkRequest := _CreatePaymentLinkRequest{}

	err = json.Unmarshal(bytes, &varCreatePaymentLinkRequest)

	if err != nil {
		return err
	}

	*o = CreatePaymentLinkRequest(varCreatePaymentLinkRequest)

	return err
}

type NullableCreatePaymentLinkRequest struct {
	value *CreatePaymentLinkRequest
	isSet bool
}

func (v NullableCreatePaymentLinkRequest) Get() *CreatePaymentLinkRequest {
	return v.value
}

func (v *NullableCreatePaymentLinkRequest) Set(val *CreatePaymentLinkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePaymentLinkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePaymentLinkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePaymentLinkRequest(val *CreatePaymentLinkRequest) *NullableCreatePaymentLinkRequest {
	return &NullableCreatePaymentLinkRequest{value: val, isSet: true}
}

func (v NullableCreatePaymentLinkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePaymentLinkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


