/*
OpenPay API

super charge your subscription management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getopenpay

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the CustomerExternal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerExternal{}

// CustomerExternal struct for CustomerExternal
type CustomerExternal struct {
	// Unique identifier of the customer.
	Id string `json:"id"`
	Object *ObjectName `json:"object,omitempty"`
	// DateTime at which the object was created, in 'ISO 8601' format.
	CreatedAt time.Time `json:"created_at"`
	// DateTime at which the object was updated, in 'ISO 8601' format.
	UpdatedAt time.Time `json:"updated_at"`
	// If true, indicates that this object has been deleted
	IsDeleted *bool `json:"is_deleted,omitempty"`
	// Unique identifier for the account.
	AccountId string `json:"account_id"`
	// Customer’s email address.
	Email string `json:"email"`
	FirstName NullableString `json:"first_name"`
	LastName NullableString `json:"last_name"`
	Address NullableCompleteAddress `json:"address"`
	Subscriptions []SubscriptionExternal `json:"subscriptions,omitempty"`
	BalanceAtoms []CustomerBalanceExternal `json:"balance_atoms,omitempty"`
	SubscribedToProducts []ProductExternal `json:"subscribed_to_products,omitempty"`
	LastSuccessfulPaymentIntent NullablePaymentIntentExternal `json:"last_successful_payment_intent,omitempty"`
	Discount NullableDiscountExternal `json:"discount,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Notes NullableString `json:"notes"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
}

type _CustomerExternal CustomerExternal

// NewCustomerExternal instantiates a new CustomerExternal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerExternal(id string, createdAt time.Time, updatedAt time.Time, accountId string, email string, firstName NullableString, lastName NullableString, address NullableCompleteAddress, notes NullableString) *CustomerExternal {
	this := CustomerExternal{}
	this.Id = id
	var object ObjectName = OBJECTNAME_CUSTOMER
	this.Object = &object
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	var isDeleted bool = false
	this.IsDeleted = &isDeleted
	this.AccountId = accountId
	this.Email = email
	this.FirstName = firstName
	this.LastName = lastName
	this.Address = address
	this.Notes = notes
	return &this
}

// NewCustomerExternalWithDefaults instantiates a new CustomerExternal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerExternalWithDefaults() *CustomerExternal {
	this := CustomerExternal{}
	var object ObjectName = OBJECTNAME_CUSTOMER
	this.Object = &object
	var isDeleted bool = false
	this.IsDeleted = &isDeleted
	return &this
}

// GetId returns the Id field value
func (o *CustomerExternal) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomerExternal) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomerExternal) SetId(v string) {
	o.Id = v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *CustomerExternal) GetObject() ObjectName {
	if o == nil || IsNil(o.Object) {
		var ret ObjectName
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerExternal) GetObjectOk() (*ObjectName, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *CustomerExternal) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given ObjectName and assigns it to the Object field.
func (o *CustomerExternal) SetObject(v ObjectName) {
	o.Object = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CustomerExternal) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CustomerExternal) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CustomerExternal) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *CustomerExternal) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *CustomerExternal) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *CustomerExternal) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *CustomerExternal) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerExternal) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *CustomerExternal) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *CustomerExternal) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

// GetAccountId returns the AccountId field value
func (o *CustomerExternal) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CustomerExternal) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CustomerExternal) SetAccountId(v string) {
	o.AccountId = v
}

// GetEmail returns the Email field value
func (o *CustomerExternal) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CustomerExternal) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CustomerExternal) SetEmail(v string) {
	o.Email = v
}

// GetFirstName returns the FirstName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CustomerExternal) GetFirstName() string {
	if o == nil || o.FirstName.Get() == nil {
		var ret string
		return ret
	}

	return *o.FirstName.Get()
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerExternal) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirstName.Get(), o.FirstName.IsSet()
}

// SetFirstName sets field value
func (o *CustomerExternal) SetFirstName(v string) {
	o.FirstName.Set(&v)
}

// GetLastName returns the LastName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CustomerExternal) GetLastName() string {
	if o == nil || o.LastName.Get() == nil {
		var ret string
		return ret
	}

	return *o.LastName.Get()
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerExternal) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastName.Get(), o.LastName.IsSet()
}

// SetLastName sets field value
func (o *CustomerExternal) SetLastName(v string) {
	o.LastName.Set(&v)
}

// GetAddress returns the Address field value
// If the value is explicit nil, the zero value for CompleteAddress will be returned
func (o *CustomerExternal) GetAddress() CompleteAddress {
	if o == nil || o.Address.Get() == nil {
		var ret CompleteAddress
		return ret
	}

	return *o.Address.Get()
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerExternal) GetAddressOk() (*CompleteAddress, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address.Get(), o.Address.IsSet()
}

// SetAddress sets field value
func (o *CustomerExternal) SetAddress(v CompleteAddress) {
	o.Address.Set(&v)
}

// GetSubscriptions returns the Subscriptions field value if set, zero value otherwise.
func (o *CustomerExternal) GetSubscriptions() []SubscriptionExternal {
	if o == nil || IsNil(o.Subscriptions) {
		var ret []SubscriptionExternal
		return ret
	}
	return o.Subscriptions
}

// GetSubscriptionsOk returns a tuple with the Subscriptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerExternal) GetSubscriptionsOk() ([]SubscriptionExternal, bool) {
	if o == nil || IsNil(o.Subscriptions) {
		return nil, false
	}
	return o.Subscriptions, true
}

// HasSubscriptions returns a boolean if a field has been set.
func (o *CustomerExternal) HasSubscriptions() bool {
	if o != nil && !IsNil(o.Subscriptions) {
		return true
	}

	return false
}

// SetSubscriptions gets a reference to the given []SubscriptionExternal and assigns it to the Subscriptions field.
func (o *CustomerExternal) SetSubscriptions(v []SubscriptionExternal) {
	o.Subscriptions = v
}

// GetBalanceAtoms returns the BalanceAtoms field value if set, zero value otherwise.
func (o *CustomerExternal) GetBalanceAtoms() []CustomerBalanceExternal {
	if o == nil || IsNil(o.BalanceAtoms) {
		var ret []CustomerBalanceExternal
		return ret
	}
	return o.BalanceAtoms
}

// GetBalanceAtomsOk returns a tuple with the BalanceAtoms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerExternal) GetBalanceAtomsOk() ([]CustomerBalanceExternal, bool) {
	if o == nil || IsNil(o.BalanceAtoms) {
		return nil, false
	}
	return o.BalanceAtoms, true
}

// HasBalanceAtoms returns a boolean if a field has been set.
func (o *CustomerExternal) HasBalanceAtoms() bool {
	if o != nil && !IsNil(o.BalanceAtoms) {
		return true
	}

	return false
}

// SetBalanceAtoms gets a reference to the given []CustomerBalanceExternal and assigns it to the BalanceAtoms field.
func (o *CustomerExternal) SetBalanceAtoms(v []CustomerBalanceExternal) {
	o.BalanceAtoms = v
}

// GetSubscribedToProducts returns the SubscribedToProducts field value if set, zero value otherwise.
func (o *CustomerExternal) GetSubscribedToProducts() []ProductExternal {
	if o == nil || IsNil(o.SubscribedToProducts) {
		var ret []ProductExternal
		return ret
	}
	return o.SubscribedToProducts
}

// GetSubscribedToProductsOk returns a tuple with the SubscribedToProducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerExternal) GetSubscribedToProductsOk() ([]ProductExternal, bool) {
	if o == nil || IsNil(o.SubscribedToProducts) {
		return nil, false
	}
	return o.SubscribedToProducts, true
}

// HasSubscribedToProducts returns a boolean if a field has been set.
func (o *CustomerExternal) HasSubscribedToProducts() bool {
	if o != nil && !IsNil(o.SubscribedToProducts) {
		return true
	}

	return false
}

// SetSubscribedToProducts gets a reference to the given []ProductExternal and assigns it to the SubscribedToProducts field.
func (o *CustomerExternal) SetSubscribedToProducts(v []ProductExternal) {
	o.SubscribedToProducts = v
}

// GetLastSuccessfulPaymentIntent returns the LastSuccessfulPaymentIntent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerExternal) GetLastSuccessfulPaymentIntent() PaymentIntentExternal {
	if o == nil || IsNil(o.LastSuccessfulPaymentIntent.Get()) {
		var ret PaymentIntentExternal
		return ret
	}
	return *o.LastSuccessfulPaymentIntent.Get()
}

// GetLastSuccessfulPaymentIntentOk returns a tuple with the LastSuccessfulPaymentIntent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerExternal) GetLastSuccessfulPaymentIntentOk() (*PaymentIntentExternal, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastSuccessfulPaymentIntent.Get(), o.LastSuccessfulPaymentIntent.IsSet()
}

// HasLastSuccessfulPaymentIntent returns a boolean if a field has been set.
func (o *CustomerExternal) HasLastSuccessfulPaymentIntent() bool {
	if o != nil && o.LastSuccessfulPaymentIntent.IsSet() {
		return true
	}

	return false
}

// SetLastSuccessfulPaymentIntent gets a reference to the given NullablePaymentIntentExternal and assigns it to the LastSuccessfulPaymentIntent field.
func (o *CustomerExternal) SetLastSuccessfulPaymentIntent(v PaymentIntentExternal) {
	o.LastSuccessfulPaymentIntent.Set(&v)
}
// SetLastSuccessfulPaymentIntentNil sets the value for LastSuccessfulPaymentIntent to be an explicit nil
func (o *CustomerExternal) SetLastSuccessfulPaymentIntentNil() {
	o.LastSuccessfulPaymentIntent.Set(nil)
}

// UnsetLastSuccessfulPaymentIntent ensures that no value is present for LastSuccessfulPaymentIntent, not even an explicit nil
func (o *CustomerExternal) UnsetLastSuccessfulPaymentIntent() {
	o.LastSuccessfulPaymentIntent.Unset()
}

// GetDiscount returns the Discount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerExternal) GetDiscount() DiscountExternal {
	if o == nil || IsNil(o.Discount.Get()) {
		var ret DiscountExternal
		return ret
	}
	return *o.Discount.Get()
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerExternal) GetDiscountOk() (*DiscountExternal, bool) {
	if o == nil {
		return nil, false
	}
	return o.Discount.Get(), o.Discount.IsSet()
}

// HasDiscount returns a boolean if a field has been set.
func (o *CustomerExternal) HasDiscount() bool {
	if o != nil && o.Discount.IsSet() {
		return true
	}

	return false
}

// SetDiscount gets a reference to the given NullableDiscountExternal and assigns it to the Discount field.
func (o *CustomerExternal) SetDiscount(v DiscountExternal) {
	o.Discount.Set(&v)
}
// SetDiscountNil sets the value for Discount to be an explicit nil
func (o *CustomerExternal) SetDiscountNil() {
	o.Discount.Set(nil)
}

// UnsetDiscount ensures that no value is present for Discount, not even an explicit nil
func (o *CustomerExternal) UnsetDiscount() {
	o.Discount.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerExternal) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerExternal) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CustomerExternal) HasMetadata() bool {
	if o != nil && IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CustomerExternal) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetNotes returns the Notes field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CustomerExternal) GetNotes() string {
	if o == nil || o.Notes.Get() == nil {
		var ret string
		return ret
	}

	return *o.Notes.Get()
}

// GetNotesOk returns a tuple with the Notes field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerExternal) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notes.Get(), o.Notes.IsSet()
}

// SetNotes sets field value
func (o *CustomerExternal) SetNotes(v string) {
	o.Notes.Set(&v)
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerExternal) GetCustomFields() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerExternal) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *CustomerExternal) HasCustomFields() bool {
	if o != nil && IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *CustomerExternal) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o CustomerExternal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerExternal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	if !IsNil(o.IsDeleted) {
		toSerialize["is_deleted"] = o.IsDeleted
	}
	toSerialize["account_id"] = o.AccountId
	toSerialize["email"] = o.Email
	toSerialize["first_name"] = o.FirstName.Get()
	toSerialize["last_name"] = o.LastName.Get()
	toSerialize["address"] = o.Address.Get()
	if !IsNil(o.Subscriptions) {
		toSerialize["subscriptions"] = o.Subscriptions
	}
	if !IsNil(o.BalanceAtoms) {
		toSerialize["balance_atoms"] = o.BalanceAtoms
	}
	if !IsNil(o.SubscribedToProducts) {
		toSerialize["subscribed_to_products"] = o.SubscribedToProducts
	}
	if o.LastSuccessfulPaymentIntent.IsSet() {
		toSerialize["last_successful_payment_intent"] = o.LastSuccessfulPaymentIntent.Get()
	}
	if o.Discount.IsSet() {
		toSerialize["discount"] = o.Discount.Get()
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["notes"] = o.Notes.Get()
	if o.CustomFields != nil {
		toSerialize["custom_fields"] = o.CustomFields
	}
	return toSerialize, nil
}

func (o *CustomerExternal) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created_at",
		"updated_at",
		"account_id",
		"email",
		"first_name",
		"last_name",
		"address",
		"notes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerExternal := _CustomerExternal{}

	err = json.Unmarshal(bytes, &varCustomerExternal)

	if err != nil {
		return err
	}

	*o = CustomerExternal(varCustomerExternal)

	return err
}

type NullableCustomerExternal struct {
	value *CustomerExternal
	isSet bool
}

func (v NullableCustomerExternal) Get() *CustomerExternal {
	return v.value
}

func (v *NullableCustomerExternal) Set(val *CustomerExternal) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerExternal) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerExternal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerExternal(val *CustomerExternal) *NullableCustomerExternal {
	return &NullableCustomerExternal{value: val, isSet: true}
}

func (v NullableCustomerExternal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerExternal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


