/*
OpenPay API

super charge your subscription management.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getopenpay

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SignupQuestionnaireStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignupQuestionnaireStatus{}

// SignupQuestionnaireStatus struct for SignupQuestionnaireStatus
type SignupQuestionnaireStatus struct {
	// DateTime at which the object was created, in 'ISO 8601' format.
	CreatedAt time.Time `json:"created_at"`
	// Unique identifier for the object.
	Id string `json:"id"`
	// If true, indicates that this object has been deleted
	IsDeleted *bool `json:"is_deleted,omitempty"`
	Object *ObjectName `json:"object,omitempty"`
	// The status of the questionnaire.
	Status bool `json:"status"`
	// DateTime at which the object was updated, in 'ISO 8601' format.
	UpdatedAt time.Time `json:"updated_at"`
}

type _SignupQuestionnaireStatus SignupQuestionnaireStatus

// NewSignupQuestionnaireStatus instantiates a new SignupQuestionnaireStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignupQuestionnaireStatus(createdAt time.Time, id string, status bool, updatedAt time.Time) *SignupQuestionnaireStatus {
	this := SignupQuestionnaireStatus{}
	this.CreatedAt = createdAt
	this.Id = id
	var isDeleted bool = false
	this.IsDeleted = &isDeleted
	this.Status = status
	this.UpdatedAt = updatedAt
	return &this
}

// NewSignupQuestionnaireStatusWithDefaults instantiates a new SignupQuestionnaireStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignupQuestionnaireStatusWithDefaults() *SignupQuestionnaireStatus {
	this := SignupQuestionnaireStatus{}
	var isDeleted bool = false
	this.IsDeleted = &isDeleted
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *SignupQuestionnaireStatus) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SignupQuestionnaireStatus) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SignupQuestionnaireStatus) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *SignupQuestionnaireStatus) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SignupQuestionnaireStatus) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SignupQuestionnaireStatus) SetId(v string) {
	o.Id = v
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *SignupQuestionnaireStatus) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignupQuestionnaireStatus) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *SignupQuestionnaireStatus) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *SignupQuestionnaireStatus) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *SignupQuestionnaireStatus) GetObject() ObjectName {
	if o == nil || IsNil(o.Object) {
		var ret ObjectName
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignupQuestionnaireStatus) GetObjectOk() (*ObjectName, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *SignupQuestionnaireStatus) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given ObjectName and assigns it to the Object field.
func (o *SignupQuestionnaireStatus) SetObject(v ObjectName) {
	o.Object = &v
}

// GetStatus returns the Status field value
func (o *SignupQuestionnaireStatus) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SignupQuestionnaireStatus) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SignupQuestionnaireStatus) SetStatus(v bool) {
	o.Status = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SignupQuestionnaireStatus) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SignupQuestionnaireStatus) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SignupQuestionnaireStatus) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o SignupQuestionnaireStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignupQuestionnaireStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["id"] = o.Id
	if !IsNil(o.IsDeleted) {
		toSerialize["is_deleted"] = o.IsDeleted
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	toSerialize["status"] = o.Status
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *SignupQuestionnaireStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"id",
		"status",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignupQuestionnaireStatus := _SignupQuestionnaireStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignupQuestionnaireStatus)

	if err != nil {
		return err
	}

	*o = SignupQuestionnaireStatus(varSignupQuestionnaireStatus)

	return err
}

type NullableSignupQuestionnaireStatus struct {
	value *SignupQuestionnaireStatus
	isSet bool
}

func (v NullableSignupQuestionnaireStatus) Get() *SignupQuestionnaireStatus {
	return v.value
}

func (v *NullableSignupQuestionnaireStatus) Set(val *SignupQuestionnaireStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSignupQuestionnaireStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSignupQuestionnaireStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignupQuestionnaireStatus(val *SignupQuestionnaireStatus) *NullableSignupQuestionnaireStatus {
	return &NullableSignupQuestionnaireStatus{value: val, isSet: true}
}

func (v NullableSignupQuestionnaireStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignupQuestionnaireStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


